#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# setup-custom-domain.sh <buyer>
#
# Wires a buyer-branded subdomain (e.g. powi.sparkconnected.com) onto a
# Vercel project, then writes the per-artifact domain-status.yml.
#
# Reusable for any buyer in system/domain-registry.json.
#
# REQUIREMENTS (one-time):
#   - VERCEL_TOKEN in system/.env.deploy  (https://vercel.com/account/tokens)
#   - VERCEL_TEAM  in system/.env.deploy  (only for team projects; blank otherwise)
#   - Network access to api.vercel.com — run on your LOCAL MACHINE,
#     NOT the Cowork sandbox (sandbox proxy blocks Vercel).
#   - jq + curl installed (default on macOS/Linux; Windows: Git Bash / WSL).
#
# USAGE:
#   ./system/setup-custom-domain.sh powi
#   ./system/setup-custom-domain.sh navitas
#
# EFFECT:
#   1. POST api.vercel.com/v10/projects/<project>/domains
#   2. Parse response -> verified / pending-verification / error code
#   3. Write artifacts/<artifact>/deployed/domain-status.yml
#   4. Print operator checklist (DNS record to add)
# ----------------------------------------------------------------------------
set -u

SYS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SYS_DIR/.." && pwd)"
REGISTRY="$SYS_DIR/domain-registry.json"
ENV_FILE="$SYS_DIR/.env.deploy"

# shellcheck disable=SC1090
[ -f "$ENV_FILE" ] && . "$ENV_FILE"

BUYER="${1:-}"
if [ -z "$BUYER" ]; then
  echo "usage: $0 <buyer-slug>"
  echo
  echo "Available buyers in registry:"
  jq -r '.buyers | keys[] | "  - \(.)"' "$REGISTRY" 2>/dev/null || echo "  (registry unreadable)"
  exit 2
fi

if [ -z "${VERCEL_TOKEN:-}" ]; then
  echo "ERROR: VERCEL_TOKEN not set in $ENV_FILE"
  echo "       Get a token at https://vercel.com/account/tokens"
  exit 1
fi

if [ ! -f "$REGISTRY" ]; then
  echo "ERROR: registry not found: $REGISTRY"
  exit 1
fi

# Pull buyer config from registry
SUBDOMAIN=$(jq -r ".buyers.$BUYER.subdomain // empty" "$REGISTRY")
PROJECT=$(jq -r ".buyers.$BUYER.vercel_project // empty" "$REGISTRY")
ARTIFACT=$(jq -r ".buyers.$BUYER.artifact // empty" "$REGISTRY")
BASE_DOMAIN=$(jq -r '.base_domain' "$REGISTRY")
VERCEL_TARGET=$(jq -r '.default_vercel_target' "$REGISTRY")

if [ -z "$SUBDOMAIN" ] || [ "$SUBDOMAIN" = "null" ]; then
  echo "ERROR: buyer '$BUYER' not in registry. Add it to: $REGISTRY"
  exit 2
fi

echo "================================================================"
echo "  CUSTOM DOMAIN SETUP — $BUYER"
echo "================================================================"
echo "  Buyer:          $BUYER"
echo "  Subdomain:      $SUBDOMAIN"
echo "  Vercel project: $PROJECT"
echo "  Artifact:       ${ARTIFACT:-(none — reserved only)}"
echo "  Base domain:    $BASE_DOMAIN"
echo

if [ -z "$ARTIFACT" ] || [ "$ARTIFACT" = "null" ]; then
  echo "INFO: buyer '$BUYER' is reserved but has no artifact deployed yet."
  echo "      Vercel API call skipped. Reservation noted."
  exit 0
fi

TEAM_QUERY=""
[ -n "${VERCEL_TEAM:-}" ] && TEAM_QUERY="?teamId=$VERCEL_TEAM"

echo ">>> POST api.vercel.com/v10/projects/$PROJECT/domains"
RESP=$(curl -sS -X POST \
  -H "Authorization: Bearer $VERCEL_TOKEN" \
  -H "Content-Type: application/json" \
  --connect-timeout 10 --max-time 25 \
  -d "{\"name\":\"$SUBDOMAIN\"}" \
  "https://api.vercel.com/v10/projects/$PROJECT/domains$TEAM_QUERY")

echo "--- Vercel response ---"
echo "$RESP" | jq . 2>/dev/null || echo "$RESP"
echo "-----------------------"

STATUS="unknown"
if echo "$RESP" | jq -e '.error' >/dev/null 2>&1; then
  ERRCODE=$(echo "$RESP" | jq -r '.error.code // "unknown"')
  case "$ERRCODE" in
    domain_already_in_use) STATUS="already-attached" ;;
    forbidden|not_found)   STATUS="error-permission-or-project-missing" ;;
    *)                     STATUS="error-$ERRCODE" ;;
  esac
elif echo "$RESP" | jq -e '.verified == true' >/dev/null 2>&1; then
  STATUS="verified"
elif echo "$RESP" | jq -e '.verified == false' >/dev/null 2>&1; then
  STATUS="pending-verification"
fi

# Update per-artifact domain-status.yml
ART_DEPLOY_DIR="$ROOT_DIR/artifacts/$ARTIFACT/deployed"
mkdir -p "$ART_DEPLOY_DIR"
STATUS_FILE="$ART_DEPLOY_DIR/domain-status.yml"

{
  echo "# Auto-generated by system/setup-custom-domain.sh"
  echo
  echo "buyer:           $BUYER"
  echo "artifact:        $ARTIFACT"
  echo "vercel_project:  $PROJECT"
  echo
  echo "canonical_url:   https://$SUBDOMAIN"
  echo "vercel_url:      https://${PROJECT}.vercel.app"
  echo "custom_domain:   $SUBDOMAIN"
  echo
  echo "setup_status:    $STATUS"
  echo "dns_status:      pending-propagation"
  echo "configured_at:   $(date -Iseconds)"
  echo
  echo "dns_records_required:"
  echo "  - type:   CNAME"
  echo "    name:   ${SUBDOMAIN%%.*}"
  echo "    value:  $VERCEL_TARGET"
  echo "    ttl:    300"
  echo "    notes:  Add at the DNS provider managing $BASE_DOMAIN"
  echo
  echo "vercel_response: |"
  echo "$RESP" | sed 's/^/  /'
} > "$STATUS_FILE"

echo "Wrote $STATUS_FILE"
echo
echo "================================================================"
echo "  NEXT STEPS"
echo "================================================================"
echo
echo "  1. Add DNS record at provider managing $BASE_DOMAIN:"
echo
echo "       Type:  CNAME"
echo "       Name:  ${SUBDOMAIN%%.*}"
echo "       Value: $VERCEL_TARGET"
echo "       TTL:   300"
echo
echo "  2. Wait 5-30 min for DNS propagation. Verify:"
echo "       dig +short $SUBDOMAIN"
echo
echo "  3. Vercel auto-issues Let's Encrypt cert. Open:"
echo "       https://$SUBDOMAIN"
echo
echo "Status: $STATUS"
